
select 'The ' || title_en ||' contains ' ||total|| ' digitised specimens of '||nb_species||' taxa. The following classes are included: '||class_taxonomic_coverage
as abstract, total as nb_specimens, nb_species, null as ig_num, ranks, null as existing_code, c.id, name, code, title_en, title_nl, title_fr, profile, path, geographic_coverage, min_lon, max_lon, min_lat, max_lat, start_date, end_date,
	'natural history collection, RBINS, DaRWIN, '::text || c.name::text AS keywords,
	'Royal Belgian Institute for Natural Sciences'::text AS institute_name,
	'Department of '::text AS institute_dept_abbrev,
	(curator.given_name::text || ' '::text) || curator.family_name::text AS boss,
	uc1.entry AS boss_email,
	'curator'::text AS boss_role,
	(staff.given_name::text || ' '::text) || staff.family_name::text AS subboss,
	uc2.entry AS subboss_email,
	'Collection manager'::text AS subboss_role, class_taxonomic_coverage from (
select id, name, name_indexed as code, title_en, title_nl, title_fr, profile, path, string_agg(DISTINCT country, ', ') as geographic_coverage, min(decimal_longitude) as min_lon, max(decimal_longitude) as max_lon, min(decimal_latitude) as min_lat, max(decimal_latitude) as max_lat, min(event_date) as start_date, max(event_date) as end_date, main_manager_ref, staff_ref, count(*) as total, count(distinct scientific_name) as nb_species, string_agg(distinct taxon_rank, ', ') as ranks, string_agg(distinct class, ', ') as class_taxonomic_coverage from darwin2.mv_darwin_ipt_rbins left join darwin2.collections c on ndwc_collection_path LIKE '%/'||c.id||'/%' where name_indexed='aves' group by id, name, name_indexed, title_en, title_nl, title_fr, profile, path
union all
select id, name, name_indexed as code, title_en, title_nl, title_fr, profile, path, string_agg(DISTINCT country, ', ') as geographic_coverage, min(decimal_longitude) as min_lon, max(decimal_longitude) as max_lon, min(decimal_latitude) as min_lat, max(decimal_latitude) as max_lat, min(event_date) as start_date, max(event_date) as end_date, main_manager_ref, staff_ref, count(*) as total, count(distinct scientific_name) as nb_species, string_agg(distinct taxon_rank, ', ') as ranks, string_agg(distinct class, ', ') as class_taxonomic_coverage from darwin2.mv_darwin_ipt_rbins left join darwin2.collections c on ndwc_collection_path LIKE '%/'||c.id||'/%' where name_indexed='belgianmarineinvertebrates' group by id, name, name_indexed, title_en, title_nl, title_fr, profile, path
union all
select id, name, name_indexed as code, title_en, title_nl, title_fr, profile, path, string_agg(DISTINCT country, ', ') as geographic_coverage, min(decimal_longitude) as min_lon, max(decimal_longitude) as max_lon, min(decimal_latitude) as min_lat, max(decimal_latitude) as max_lat, min(event_date) as start_date, max(event_date) as end_date, main_manager_ref, staff_ref, count(*) as total, count(distinct scientific_name) as nb_species, string_agg(distinct taxon_rank, ', ') as ranks, string_agg(distinct class, ', ') as class_taxonomic_coverage from darwin2.mv_darwin_ipt_rbins left join darwin2.collections c on ndwc_collection_path LIKE '%/'||c.id||'/%' where name_indexed='brachiopoda' group by id, name, name_indexed, title_en, title_nl, title_fr, profile, path
union all
select id, name, name_indexed as code, title_en, title_nl, title_fr, profile, path, string_agg(DISTINCT country, ', ') as geographic_coverage, min(decimal_longitude) as min_lon, max(decimal_longitude) as max_lon, min(decimal_latitude) as min_lat, max(decimal_latitude) as max_lat, min(event_date) as start_date, max(event_date) as end_date, main_manager_ref, staff_ref, count(*) as total, count(distinct scientific_name) as nb_species, string_agg(distinct taxon_rank, ', ') as ranks, string_agg(distinct class, ', ') as class_taxonomic_coverage from darwin2.mv_darwin_ipt_rbins left join darwin2.collections c on ndwc_collection_path LIKE '%/'||c.id||'/%' where name_indexed='bryozoa' group by id, name, name_indexed, title_en, title_nl, title_fr, profile, path
union all
select id, name, name_indexed as code, title_en, title_nl, title_fr, profile, path, string_agg(DISTINCT country, ', ') as geographic_coverage, min(decimal_longitude) as min_lon, max(decimal_longitude) as max_lon, min(decimal_latitude) as min_lat, max(decimal_latitude) as max_lat, min(event_date) as start_date, max(event_date) as end_date, main_manager_ref, staff_ref, count(*) as total, count(distinct scientific_name) as nb_species, string_agg(distinct taxon_rank, ', ') as ranks, string_agg(distinct class, ', ') as class_taxonomic_coverage from darwin2.mv_darwin_ipt_rbins left join darwin2.collections c on ndwc_collection_path LIKE '%/'||c.id||'/%' where name_indexed='cheliceratamarine' group by id, name, name_indexed, title_en, title_nl, title_fr, profile, path
union all
select id, name, name_indexed as code, title_en, title_nl, title_fr, profile, path, string_agg(DISTINCT country, ', ') as geographic_coverage, min(decimal_longitude) as min_lon, max(decimal_longitude) as max_lon, min(decimal_latitude) as min_lat, max(decimal_latitude) as max_lat, min(event_date) as start_date, max(event_date) as end_date, main_manager_ref, staff_ref, count(*) as total, count(distinct scientific_name) as nb_species, string_agg(distinct taxon_rank, ', ') as ranks, string_agg(distinct class, ', ') as class_taxonomic_coverage from darwin2.mv_darwin_ipt_rbins left join darwin2.collections c on ndwc_collection_path LIKE '%/'||c.id||'/%' where name_indexed='cnidaria' group by id, name, name_indexed, title_en, title_nl, title_fr, profile, path
union all
select id, name, name_indexed as code, title_en, title_nl, title_fr, profile, path, string_agg(DISTINCT country, ', ') as geographic_coverage, min(decimal_longitude) as min_lon, max(decimal_longitude) as max_lon, min(decimal_latitude) as min_lat, max(decimal_latitude) as max_lat, min(event_date) as start_date, max(event_date) as end_date, main_manager_ref, staff_ref, count(*) as total, count(distinct scientific_name) as nb_species, string_agg(distinct taxon_rank, ', ') as ranks, string_agg(distinct class, ', ') as class_taxonomic_coverage from darwin2.mv_darwin_ipt_rbins left join darwin2.collections c on ndwc_collection_path LIKE '%/'||c.id||'/%' where name_indexed='crustacea' group by id, name, name_indexed, title_en, title_nl, title_fr, profile, path
union all
select id, name, name_indexed as code, title_en, title_nl, title_fr, profile, path, string_agg(DISTINCT country, ', ') as geographic_coverage, min(decimal_longitude) as min_lon, max(decimal_longitude) as max_lon, min(decimal_latitude) as min_lat, max(decimal_latitude) as max_lat, min(event_date) as start_date, max(event_date) as end_date, main_manager_ref, staff_ref, count(*) as total, count(distinct scientific_name) as nb_species, string_agg(distinct taxon_rank, ', ') as ranks, string_agg(distinct class, ', ') as class_taxonomic_coverage from darwin2.mv_darwin_ipt_rbins left join darwin2.collections c on ndwc_collection_path LIKE '%/'||c.id||'/%' where name_indexed='echinodermata' group by id, name, name_indexed, title_en, title_nl, title_fr, profile, path
union all
select id, name, name_indexed as code, title_en, title_nl, title_fr, profile, path, string_agg(DISTINCT country, ', ') as geographic_coverage, min(decimal_longitude) as min_lon, max(decimal_longitude) as max_lon, min(decimal_latitude) as min_lat, max(decimal_latitude) as max_lat, min(event_date) as start_date, max(event_date) as end_date, main_manager_ref, staff_ref, count(*) as total, count(distinct scientific_name) as nb_species, string_agg(distinct taxon_rank, ', ') as ranks, string_agg(distinct class, ', ') as class_taxonomic_coverage from darwin2.mv_darwin_ipt_rbins left join darwin2.collections c on ndwc_collection_path LIKE '%/'||c.id||'/%' where name_indexed='mammalia' group by id, name, name_indexed, title_en, title_nl, title_fr, profile, path
union all
select id, name, name_indexed as code, title_en, title_nl, title_fr, profile, path, string_agg(DISTINCT country, ', ') as geographic_coverage, min(decimal_longitude) as min_lon, max(decimal_longitude) as max_lon, min(decimal_latitude) as min_lat, max(decimal_latitude) as max_lat, min(event_date) as start_date, max(event_date) as end_date, main_manager_ref, staff_ref, count(*) as total, count(distinct scientific_name) as nb_species, string_agg(distinct taxon_rank, ', ') as ranks, string_agg(distinct class, ', ') as class_taxonomic_coverage from darwin2.mv_darwin_ipt_rbins left join darwin2.collections c on ndwc_collection_path LIKE '%/'||c.id||'/%' where name_indexed='mollusca' group by id, name, name_indexed, title_en, title_nl, title_fr, profile, path
union all
select id, name, name_indexed as code, title_en, title_nl, title_fr, profile, path, string_agg(DISTINCT country, ', ') as geographic_coverage, min(decimal_longitude) as min_lon, max(decimal_longitude) as max_lon, min(decimal_latitude) as min_lat, max(decimal_latitude) as max_lat, min(event_date) as start_date, max(event_date) as end_date, main_manager_ref, staff_ref, count(*) as total, count(distinct scientific_name) as nb_species, string_agg(distinct taxon_rank, ', ') as ranks, string_agg(distinct class, ', ') as class_taxonomic_coverage from darwin2.mv_darwin_ipt_rbins left join darwin2.collections c on ndwc_collection_path LIKE '%/'||c.id||'/%' where name_indexed='pisces' group by id, name, name_indexed, title_en, title_nl, title_fr, profile, path
union all
select id, name, name_indexed as code, title_en, title_nl, title_fr, profile, path, string_agg(DISTINCT country, ', ') as geographic_coverage, min(decimal_longitude) as min_lon, max(decimal_longitude) as max_lon, min(decimal_latitude) as min_lat, max(decimal_latitude) as max_lat, min(event_date) as start_date, max(event_date) as end_date, main_manager_ref, staff_ref, count(*) as total, count(distinct scientific_name) as nb_species, string_agg(distinct taxon_rank, ', ') as ranks, string_agg(distinct class, ', ') as class_taxonomic_coverage from darwin2.mv_darwin_ipt_rbins left join darwin2.collections c on ndwc_collection_path LIKE '%/'||c.id||'/%' where name_indexed='reptilia' group by id, name, name_indexed, title_en, title_nl, title_fr, profile, path
union all
select id, name, name_indexed as code, title_en, title_nl, title_fr, profile, path, string_agg(DISTINCT country, ', ') as geographic_coverage, min(decimal_longitude) as min_lon, max(decimal_longitude) as max_lon, min(decimal_latitude) as min_lat, max(decimal_latitude) as max_lat, min(event_date) as start_date, max(event_date) as end_date, main_manager_ref, staff_ref, count(*) as total, count(distinct scientific_name) as nb_species, string_agg(distinct taxon_rank, ', ') as ranks, string_agg(distinct class, ', ') as class_taxonomic_coverage from darwin2.mv_darwin_ipt_rbins left join darwin2.collections c on ndwc_collection_path LIKE '%/'||c.id||'/%' where name_indexed='rotifera' group by id, name, name_indexed, title_en, title_nl, title_fr, profile, path
union all
select id, name, name_indexed as code, title_en, title_nl, title_fr, profile, path, string_agg(DISTINCT country, ', ') as geographic_coverage, min(decimal_longitude) as min_lon, max(decimal_longitude) as max_lon, min(decimal_latitude) as min_lat, max(decimal_latitude) as max_lat, min(event_date) as start_date, max(event_date) as end_date, main_manager_ref, staff_ref, count(*) as total, count(distinct scientific_name) as nb_species, string_agg(distinct taxon_rank, ', ') as ranks, string_agg(distinct class, ', ') as class_taxonomic_coverage from darwin2.mv_darwin_ipt_rbins left join darwin2.collections c on ndwc_collection_path LIKE '%/'||c.id||'/%' where name_indexed='vertebratestypes' group by id, name, name_indexed, title_en, title_nl, title_fr, profile, path
union all
select id, name, name_indexed as code, title_en, title_nl, title_fr, profile, path, string_agg(DISTINCT country, ', ') as geographic_coverage, min(decimal_longitude) as min_lon, max(decimal_longitude) as max_lon, min(decimal_latitude) as min_lat, max(decimal_latitude) as max_lat, min(event_date) as start_date, max(event_date) as end_date, main_manager_ref, staff_ref, count(*) as total, count(distinct scientific_name) as nb_species, string_agg(distinct taxon_rank, ', ') as ranks, string_agg(distinct class, ', ') as class_taxonomic_coverage from darwin2.mv_darwin_ipt_rbins left join darwin2.collections c on ndwc_collection_path LIKE '%/'||c.id||'/%' where name_indexed='acari' group by id, name, name_indexed, title_en, title_nl, title_fr, profile, path
union all
select id, name, name_indexed as code, title_en, title_nl, title_fr, profile, path, string_agg(DISTINCT country, ', ') as geographic_coverage, min(decimal_longitude) as min_lon, max(decimal_longitude) as max_lon, min(decimal_latitude) as min_lat, max(decimal_latitude) as max_lat, min(event_date) as start_date, max(event_date) as end_date, main_manager_ref, staff_ref, count(*) as total, count(distinct scientific_name) as nb_species, string_agg(distinct taxon_rank, ', ') as ranks, string_agg(distinct class, ', ') as class_taxonomic_coverage from darwin2.mv_darwin_ipt_rbins left join darwin2.collections c on ndwc_collection_path LIKE '%/'||c.id||'/%' where name_indexed='amphibia' group by id, name, name_indexed, title_en, title_nl, title_fr, profile, path
union all
select id, name, name_indexed as code, title_en, title_nl, title_fr, profile, path, string_agg(DISTINCT country, ', ') as geographic_coverage, min(decimal_longitude) as min_lon, max(decimal_longitude) as max_lon, min(decimal_latitude) as min_lat, max(decimal_latitude) as max_lat, min(event_date) as start_date, max(event_date) as end_date, main_manager_ref, staff_ref, count(*) as total, count(distinct scientific_name) as nb_species, string_agg(distinct taxon_rank, ', ') as ranks, string_agg(distinct class, ', ') as class_taxonomic_coverage from darwin2.mv_darwin_ipt_rbins left join darwin2.collections c on ndwc_collection_path LIKE '%/'||c.id||'/%' where name_indexed='araneae' group by id, name, name_indexed, title_en, title_nl, title_fr, profile, path
union all
select id, name, name_indexed as code, title_en, title_nl, title_fr, profile, path, string_agg(DISTINCT country, ', ') as geographic_coverage, min(decimal_longitude) as min_lon, max(decimal_longitude) as max_lon, min(decimal_latitude) as min_lat, max(decimal_latitude) as max_lat, min(event_date) as start_date, max(event_date) as end_date, main_manager_ref, staff_ref, count(*) as total, count(distinct scientific_name) as nb_species, string_agg(distinct taxon_rank, ', ') as ranks, string_agg(distinct class, ', ') as class_taxonomic_coverage from darwin2.mv_darwin_ipt_rbins left join darwin2.collections c on ndwc_collection_path LIKE '%/'||c.id||'/%' where name_indexed='coleoptera' group by id, name, name_indexed, title_en, title_nl, title_fr, profile, path
union all
select id, name, name_indexed as code, title_en, title_nl, title_fr, profile, path, string_agg(DISTINCT country, ', ') as geographic_coverage, min(decimal_longitude) as min_lon, max(decimal_longitude) as max_lon, min(decimal_latitude) as min_lat, max(decimal_latitude) as max_lat, min(event_date) as start_date, max(event_date) as end_date, main_manager_ref, staff_ref, count(*) as total, count(distinct scientific_name) as nb_species, string_agg(distinct taxon_rank, ', ') as ranks, string_agg(distinct class, ', ') as class_taxonomic_coverage from darwin2.mv_darwin_ipt_rbins left join darwin2.collections c on ndwc_collection_path LIKE '%/'||c.id||'/%' where name_indexed='diptera' group by id, name, name_indexed, title_en, title_nl, title_fr, profile, path
union all
select id, name, name_indexed as code, title_en, title_nl, title_fr, profile, path, string_agg(DISTINCT country, ', ') as geographic_coverage, min(decimal_longitude) as min_lon, max(decimal_longitude) as max_lon, min(decimal_latitude) as min_lat, max(decimal_latitude) as max_lat, min(event_date) as start_date, max(event_date) as end_date, main_manager_ref, staff_ref, count(*) as total, count(distinct scientific_name) as nb_species, string_agg(distinct taxon_rank, ', ') as ranks, string_agg(distinct class, ', ') as class_taxonomic_coverage from darwin2.mv_darwin_ipt_rbins left join darwin2.collections c on ndwc_collection_path LIKE '%/'||c.id||'/%' where name_indexed='heterocera' group by id, name, name_indexed, title_en, title_nl, title_fr, profile, path
union all
select id, name, name_indexed as code, title_en, title_nl, title_fr, profile, path, string_agg(DISTINCT country, ', ') as geographic_coverage, min(decimal_longitude) as min_lon, max(decimal_longitude) as max_lon, min(decimal_latitude) as min_lat, max(decimal_latitude) as max_lat, min(event_date) as start_date, max(event_date) as end_date, main_manager_ref, staff_ref, count(*) as total, count(distinct scientific_name) as nb_species, string_agg(distinct taxon_rank, ', ') as ranks, string_agg(distinct class, ', ') as class_taxonomic_coverage from darwin2.mv_darwin_ipt_rbins left join darwin2.collections c on ndwc_collection_path LIKE '%/'||c.id||'/%' where name_indexed='hymenoptera' group by id, name, name_indexed, title_en, title_nl, title_fr, profile, path
union all
select id, name, name_indexed as code, title_en, title_nl, title_fr, profile, path, string_agg(DISTINCT country, ', ') as geographic_coverage, min(decimal_longitude) as min_lon, max(decimal_longitude) as max_lon, min(decimal_latitude) as min_lat, max(decimal_latitude) as max_lat, min(event_date) as start_date, max(event_date) as end_date, main_manager_ref, staff_ref, count(*) as total, count(distinct scientific_name) as nb_species, string_agg(distinct taxon_rank, ', ') as ranks, string_agg(distinct class, ', ') as class_taxonomic_coverage from darwin2.mv_darwin_ipt_rbins left join darwin2.collections c on ndwc_collection_path LIKE '%/'||c.id||'/%' where name_indexed='orthoptera' group by id, name, name_indexed, title_en, title_nl, title_fr, profile, path
union all
select id, name, name_indexed as code, title_en, title_nl, title_fr, profile, path, string_agg(DISTINCT country, ', ') as geographic_coverage, min(decimal_longitude) as min_lon, max(decimal_longitude) as max_lon, min(decimal_latitude) as min_lat, max(decimal_latitude) as max_lat, min(event_date) as start_date, max(event_date) as end_date, main_manager_ref, staff_ref, count(*) as total, count(distinct scientific_name) as nb_species, string_agg(distinct taxon_rank, ', ') as ranks, string_agg(distinct class, ', ') as class_taxonomic_coverage from darwin2.mv_darwin_ipt_rbins left join darwin2.collections c on ndwc_collection_path LIKE '%/'||c.id||'/%' where name_indexed='rhopalocera' group by id, name, name_indexed, title_en, title_nl, title_fr, profile, path
) c 
     LEFT JOIN darwin2.users curator ON c.main_manager_ref = curator.id
     LEFT JOIN darwin2.users_comm uc1 ON uc1.person_user_ref = curator.id AND uc1.comm_type::text = 'e-mail'::text
     LEFT JOIN darwin2.users staff ON c.staff_ref = staff.id
     LEFT JOIN darwin2.users_comm uc2 ON uc2.person_user_ref = staff.id AND uc2.comm_type::text = 'e-mail'::text
order by 1



--"The Royal Belgian Institute of Natural Sciences Vertebrates/Types collection contains 2996 digitised specimens of 748 taxa (at genus, species, sub species, variety level). The following class_taxonomic_coverage are included: Actinopterygii, Amphibia Linnaeus, 1758, Aves, Chondrichtyes, Mammalia Linnaeus, 1758, Reptilia Laurenti, 1768, Sarcopterygii."
